### ISSUE TITLE
Missing permission: MESSAGE_SEND

### ISSUE THREAD

**Issue by megoRU** [megoRU/HangmanDiscordBot#138]
```
2022-08-19 04:05:56.572 ERROR 1 --- [inWS-ReadThread] net.dv8tion.jda.api.JDA : One of the EventListeners had an uncaught exception

net.dv8tion.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_SEND
        at net.dv8tion.jda.internal.entities.mixin.channel.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:63) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.entities.mixin.channel.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:55) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.entities.mixin.channel.middleman.GuildMessageChannelMixin.checkCanSendMessage(GuildMessageChannelMixin.java:131) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.entities.mixin.channel.middleman.MessageChannelMixin.sendMessage(MessageChannelMixin.java:126) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at main.eventlisteners.DeprecatedCommands.onMessageReceived(DeprecatedCommands.java:51) ~[classes!/:0.0.1-SNAPSHOT]
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:133) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992) ~[JDA-5.0.0-alpha.17.jar!/:5.0.0-alpha.17]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[nv-websocket-client-2.14.jar!/:na]

```

**Comment by megoRU** [comment]
This class deleted https://github.com/megoRU/HangmanDiscordBot/commit/dae7834cc68fc5a5a84afdff3de17d0d36eafec2#diff-cfd1fd0e5d459a549bfb94c59d2fb22bbe87150b2f5b90f94d3c32e17ff44733
