### ISSUE TITLE
Cannot invoke "String.equals(Object)" because the return value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by megoRU** [megoRU/HangmanDiscordBot#217]
```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.util.Map.get(Object)" is null
        at main.hangman.impl.EndGameButtons.getListButtons(EndGameButtons.java:16)
        at main.hangman.Hangman$StopHangmanTimer.run(Hangman.java:711)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
```
```
messageList: [M:Noman#5959:No problem(1037404611222446170), M:Noman#5959:Your back(1037442836339114026), M:Noman#5959:LMAO(1037444528279388212)]
2022-11-02 19:36:36.338  INFO 1 --- [inWS-ReadThread] main.hangman.Hangman                     : Cannot invoke "String.equals(Object)" because the return value of "java.util.Map.get(Object)" is null
2022-11-02 19:36:41.498  INFO 1 --- [inWS-ReadThread] main.hangman.Hangman                     : Cannot invoke "String.equals(Object)" because the return value of "java.util.Map.get(Object)" is null
2022-11-02 19:43:48.506  INFO 1 --- [inWS-ReadThread] main.hangman.Hangman                     : Cannot invoke "String.equals(Object)" because the return value of "java.util.Map.get(Object)" is null
2022-11-02 19:43:51.173  INFO 1 --- [      Timer-117] main.hangman.Hangman                     :
AutoDeletingMessages: 3

```

**Comment by megoRU** [comment]
```2022-11-11 19:02:32.523  INFO 1 --- [inWS-ReadThread] main.hangman.Hangman: Cannot invoke "String.equals(Object)" because the return value of "java.util.Map.get(Object)" is null```
