### ISSUE TITLE
Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_SEND_IN_THREADS

### ISSUE THREAD

**Issue by megoRU** [megoRU/HangmanDiscordBot#235]
```
net.dv8tion.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_SEND_IN_THREADS
        at net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:64)
        at net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:56)
        at net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildMessageChannelMixin.checkCanSendMessage(GuildMessageChannelMixin.java:131)
        at net.dv8tion.jda.internal.entities.channel.mixin.middleman.MessageChannelMixin.sendMessage(MessageChannelMixin.java:134)
        at main.eventlisteners.ChecksClass.canSendHG(ChecksClass.java:60)
        at main.eventlisteners.GameHangmanListener.onMessageReceived(GameHangmanListener.java:24)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:424)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:173)
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:136)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:965)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:851)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:829)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1004)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
        
```

**Comment by megoRU** [comment]
```
net.dv8tion.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_SEND_IN_THRE                                                                                  ADS
        at net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:64)
        at net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:56)
        at net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildMessageChannelMixin.checkCanSendMessage(GuildMessageChannelMixin.java:131)
        at net.dv8tion.jda.internal.entities.channel.mixin.middleman.MessageChannelMixin.sendMessage(MessageChannelMixin.java:134)
        at main.eventlisteners.ChecksClass.check(ChecksClass.java:87)
        at main.eventlisteners.GameHangmanListener.onMessageReceived(GameHangmanListener.java:33)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:424)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:173)
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:136)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:965)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:851)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:829)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1004)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

```
