### ISSUE TITLE
java.lang.IllegalStateException: This message event did not happen in a text channel

### ISSUE THREAD

**Issue by megoRU** [megoRU/HangmanDiscordBot#47]
```
java.lang.IllegalStateException: This message event did not happen in a text channel
        at net.dv8tion.jda.api.events.message.GenericMessageEvent.getTextChannel(GenericMessageEvent.java:177) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-alp                                                                                           ha.5]
        at main.hangman.GameHangmanListener.onMessageReceived(GameHangmanListener.java:38) ~[classes!/:0.0.1-SNAPSHOT]
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:359) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-alpha.5]
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-alpha.5]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-alpha.5]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-alpha.5]
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:165) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-alpha.5]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:111) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-al                                                                                           pha.5]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-alpha.5]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-alpha.5]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-alpha.5]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-alpha.5]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992) ~[JDA-5.0.0-alpha.5.jar!/:5.0.0-alpha.5]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[nv-websocket-client-2.14.jar!/:na]
```

**Comment by megoRU** [comment]
again
```
2022-03-02 21:11:32.147 ERROR 1 --- [inWS-ReadThread] net.dv8tion.jda.api.JDA                  : One of the EventListeners had an uncaught exception

java.lang.IllegalStateException: This message event did not happen in a text channel
        at net.dv8tion.jda.api.events.message.GenericMessageEvent.getTextChannel(GenericMessageEvent.java:177) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at main.hangman.GameHangmanListener.onMessageReceived(GameHangmanListener.java:38) ~[classes!/:0.0.1-SNAPSHOT]
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:359) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:164) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:114) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991) ~[JDA-5.0.0-alpha.8.jar!/:5.0.0-alpha.8]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[nv-websocket-client-2.14.jar!/:na]


```
