### ISSUE TITLE
net.dv8tion.jda.api.JDA.getGuildById(String)" is null

### ISSUE THREAD

**Issue by megoRU** [megoRU/HangmanDiscordBot#96]
```
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.Guild.getSelfMember()" because the return value of "net.dv8tion.jda.api.JDA.getGuildById(String)" is null
        at main.hangman.Hangman.deleteMessages(Hangman.java:228)
        at main.hangman.Hangman$1.run(Hangman.java:212)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

```

**Comment by megoRU** [comment]
#70
